# fly.toml app configuration file generated for reportjewel on 2024-02-27T00:43:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reportjewel'
primary_region = 'ewr'

[build]
  image = 'wushywushy/reportjewel:latest'

[env]
  ASPNETCORE_URLS = 'http://+:8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
